# rpmrebuild autogenerated specfile

%define defaultbuildroot /
AutoProv: no
%undefine __find_provides
AutoReq: no
%undefine __find_requires
# Do not try autogenerate prereq/conflicts/obsoletes and check files
%undefine __check_files
%undefine __find_prereq
%undefine __find_conflicts
%undefine __find_obsoletes
# Be sure buildpolicy set to do nothing
%define __spec_install_post %{nil}
# Something that need for rpm-4.1
%define _missing_doc_files_terminate_build 0
#dummy
#dummy
#BUILDHOST:    3f07106c86e5
#BUILDTIME:    Wed Dec 15 21:16:55 2021
#SOURCERPM:    consul-1.10.6-1.src.rpm

#RPMVERSION:   4.14.2.1



#OS:           linux
#SIZE:           105068223
#ARCHIVESIZE:           105068904
#ARCH:         x86_64
BuildArch:     x86_64
Name:          consul
Version:       1.10.6.1wf
Release:       1
License:       MPL-2.0
Group:         default
Summary:       Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure. Please submit issues to https://github.com/hashicorp/consul/issues


URL:           https://www.consul.io/
Vendor:        HashiCorp
Packager:      Wayfair <bwaters@wayfair.com>





Prefix:        /
Provides:      consul = 1.10.6.1wf-1
Provides:      consul(x86-64) = 1.10.6.1wf-1
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      /bin/sh
Requires:      openssl
#Requires:      rpmlib(CompressedFileNames) <= 3.0.4-1
#Requires:      rpmlib(PayloadFilesHavePrefix) <= 4.0-1
#Requires:      rpmlib(PayloadIsXz) <= 5.2-1
Requires:      shadow-utils
#suggest
#enhance
%description
Consul is a distributed, highly available, and data center aware solution to connect and configure applications across dynamic, distributed infrastructure. Please submit issues to https://github.com/hashicorp/consul/issues
%files
%config(noreplace) %attr(0644, root, root) "/etc/consul.d/consul.env"
%config(noreplace) %attr(0644, root, root) "/etc/consul.d/consul.hcl"
%attr(0755, root, root) "/usr/bin/consul"
%config(noreplace) %attr(0644, root, root) "/usr/lib/systemd/system/consul.service"
%pre -p /bin/sh
#!/bin/bash

set -eu

USER="consul"

if ! id -u $USER > /dev/null 2>&1; then
	useradd \
		--system \
		--user-group \
		--shell /bin/false \
		$USER
fi
%post -p /bin/sh
#!/bin/bash

mkdir -p /opt/consul
chown -R consul:consul /opt/consul
chown -R consul:consul /etc/consul.d

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if [[ $(consul version) == *+ent* ]]; then
echo "
The following shall apply unless your organization has a separately signed Enterprise License Agreement or Evaluation Agreement governing your use of the software:

Software in this repository is subject to the license terms located in the software, copies of which are also available at https://eula.hashicorp.com/ClickThruELA-Global.pdf or https://www.hashicorp.com/terms-of-evaluation as applicable. Please read the license terms prior to using the software. Your installation and use of the software constitutes your acceptance of these terms. If you do not accept the terms, do not use the software.
"
fi
%postun -p /bin/sh
#!/bin/bash

if [ "$1" = "purge" ]
then
  userdel consul
fi

if [ "$1" == "upgrade" ] && [ -d /run/systemd/system ]; then
  systemctl --system daemon-reload >/dev/null || true
  systemctl restart consul >/dev/null || true
fi

exit 0
%changelog